export const DEVICE_EVIDENCE_CATEGORIES = {
  BOOT: 'boot',
  RESET: 'reset',
  PANIC: 'panic',
  WATCHDOG: 'watchdog',
  WIFI: 'wifi',
  DISPLAY: 'display',
  OTA: 'ota',
  BLE_OTA: 'ble-ota',
  DELIVERY: 'delivery',
  DRIVER: 'driver',
  UNKNOWN: 'unknown',
}

export const DEVICE_EVIDENCE_STATUS = {
  OBSERVED: 'observed',
  SUCCESS: 'success',
  FAILURE: 'failure',
  QUEUED: 'queued',
}

export const DEVICE_LOG_PATTERNS = [
  {
    kind: 'idf-boot',
    category: DEVICE_EVIDENCE_CATEGORIES.BOOT,
    status: DEVICE_EVIDENCE_STATUS.OBSERVED,
    severity: 'info',
    pattern: /\bboot:\s*ESP-IDF\b|\bESP-IDF\b.*\bbootloader\b/i,
  },
  {
    kind: 'app-start',
    category: DEVICE_EVIDENCE_CATEGORIES.BOOT,
    status: DEVICE_EVIDENCE_STATUS.OBSERVED,
    severity: 'info',
    pattern: /\bapp_main\b|Starting scheduler|main_task: Started/i,
  },
  {
    kind: 'software-reset',
    category: DEVICE_EVIDENCE_CATEGORIES.RESET,
    status: DEVICE_EVIDENCE_STATUS.OBSERVED,
    severity: 'warning',
    pattern: /\brst:.*\bSW_CPU_RESET\b/i,
  },
  {
    kind: 'reset',
    category: DEVICE_EVIDENCE_CATEGORIES.RESET,
    status: DEVICE_EVIDENCE_STATUS.OBSERVED,
    severity: 'warning',
    pattern: /\brst:\s*0x[0-9a-f]+|Reset reason/i,
  },
  {
    kind: 'guru-meditation',
    category: DEVICE_EVIDENCE_CATEGORIES.PANIC,
    status: DEVICE_EVIDENCE_STATUS.FAILURE,
    severity: 'error',
    repairable: true,
    pattern: /Guru Meditation Error|panic'ed|abort\(\) was called|Unhandled debug exception|stack smashing protect failure/i,
  },
  {
    kind: 'backtrace',
    category: DEVICE_EVIDENCE_CATEGORIES.PANIC,
    status: DEVICE_EVIDENCE_STATUS.FAILURE,
    severity: 'error',
    repairable: true,
    pattern: /^Backtrace:|\bBacktrace:\s*0x[0-9a-f]+/i,
  },
  {
    kind: 'task-watchdog',
    category: DEVICE_EVIDENCE_CATEGORIES.WATCHDOG,
    status: DEVICE_EVIDENCE_STATUS.FAILURE,
    severity: 'error',
    repairable: true,
    pattern: /task_wdt|Task watchdog|watchdog got triggered|Interrupt wdt timeout|TWDT/i,
  },
  {
    kind: 'wifi-got-ip',
    category: DEVICE_EVIDENCE_CATEGORIES.WIFI,
    status: DEVICE_EVIDENCE_STATUS.SUCCESS,
    severity: 'info',
    pattern: /\bgot ip\b|IP_EVENT_STA_GOT_IP/i,
    details: line => ({
      ip: line.match(/\b(?:got ip[:=\s]+|ip[:=\s]+)(\d{1,3}(?:\.\d{1,3}){3})\b/i)?.[1] || null,
    }),
  },
  {
    kind: 'wifi-disconnected',
    category: DEVICE_EVIDENCE_CATEGORIES.WIFI,
    status: DEVICE_EVIDENCE_STATUS.FAILURE,
    severity: 'warning',
    repairable: true,
    pattern: /\bwifi\b.*\bdisconnect(?:ed)?\b|WIFI_EVENT_STA_DISCONNECTED/i,
    details: line => ({
      reason: line.match(/\breason[=:]\s*([0-9A-Za-z_/-]+)/i)?.[1] || null,
    }),
  },
  {
    kind: 'lvgl-error',
    category: DEVICE_EVIDENCE_CATEGORIES.DISPLAY,
    status: DEVICE_EVIDENCE_STATUS.FAILURE,
    severity: 'error',
    repairable: true,
    pattern: /\blvgl\b.*(?:error|fail|invalid|assert|not ready|before display init)|lv_display_|lv_obj_/i,
  },
  {
    kind: 'display-driver-failure',
    category: DEVICE_EVIDENCE_CATEGORIES.DISPLAY,
    status: DEVICE_EVIDENCE_STATUS.FAILURE,
    severity: 'error',
    repairable: true,
    pattern: /\b(?:lcd|display|esp_lcd|panel)\b.*(?:fail|error|invalid|timeout|not init)/i,
  },
  {
    kind: 'ble-ota-success',
    category: DEVICE_EVIDENCE_CATEGORIES.BLE_OTA,
    status: DEVICE_EVIDENCE_STATUS.SUCCESS,
    severity: 'info',
    pattern: /\b(?:ble_ota|BLE OTA)\b.*(?:success|complete|committed|commit complete|notify_code 0x00)/i,
  },
  {
    kind: 'ble-ota-failure',
    category: DEVICE_EVIDENCE_CATEGORIES.BLE_OTA,
    status: DEVICE_EVIDENCE_STATUS.FAILURE,
    severity: 'error',
    repairable: true,
    pattern: /\b(?:ble_ota|BLE OTA)\b.*(?:fail|error|invalid|abort|timeout)|notify_code 0x0[12]/i,
  },
  {
    kind: 'ota-success',
    category: DEVICE_EVIDENCE_CATEGORIES.OTA,
    status: DEVICE_EVIDENCE_STATUS.SUCCESS,
    severity: 'info',
    pattern: /\b(?:esp_https_ota|esp_ota|OTA)\b.*(?:successful|success|complete|rebooting)|Firmware upgrade successful/i,
  },
  {
    kind: 'ota-failure',
    category: DEVICE_EVIDENCE_CATEGORIES.OTA,
    status: DEVICE_EVIDENCE_STATUS.FAILURE,
    severity: 'error',
    repairable: true,
    pattern: /\b(?:esp_https_ota|esp_ota|OTA)\b.*(?:fail|error|invalid|timeout|abort)|ESP_ERR_HTTPS|ESP_ERR_OTA/i,
  },
  {
    kind: 'driver-init-success',
    category: DEVICE_EVIDENCE_CATEGORIES.DRIVER,
    status: DEVICE_EVIDENCE_STATUS.SUCCESS,
    severity: 'info',
    pattern: /\b(?:driver|lcd|display|i2c|spi|camera|audio|sdcard|esp32_s3_szp)\b.*(?:init(?:ialized)?|start(?:ed)?|install(?:ed)?)\s*(?:ok|success|done)|BSP.*ready/i,
  },
  {
    kind: 'driver-init-failure',
    category: DEVICE_EVIDENCE_CATEGORIES.DRIVER,
    status: DEVICE_EVIDENCE_STATUS.FAILURE,
    severity: 'error',
    repairable: true,
    pattern: /\b(?:driver|lcd|display|i2c|spi|camera|audio|sdcard|esp32_s3_szp)\b.*(?:init|start|install|probe).*(?:fail|error|invalid|timeout)|ESP_ERR_INVALID_ARG|ESP_ERR_NOT_FOUND/i,
  },
]
